In [33]:
import numpy as np
import pandas as pd
base = "../../data/raw/"
pd.set_option('display.max_rows', 200)

In [16]:
import os
tweetdf =pd.read_csv(os.path.join(base, "tweet.csv"),header=0)

In [17]:
loctweetdf = tweetdf.loc[tweetdf['lat'].notnull(),:]
loctweetdf

,id,time,created_at,from_user_name,text,filter_level,possibly_sensitive,withheld_copyright,withheld_scope,truncated,...,from_user_utcoffset,from_user_timezone,from_user_lang,from_user_tweetcount,from_user_followercount,from_user_friendcount,from_user_favourites_count,from_user_listed,from_user_withheld_scope,from_user_created_at
1,951300448031473664,1515642675,2018-01-11 03:51:15,Markfchris,Things to do on hot day in Sydney. @ Carriagew...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,14953,695,1725,2615,62,NaN,2010-04-22 02:37:40
4,951300560812113920,1515642702,2018-01-11 03:51:42,ZKII_,BB And The Blips x The Red Rattler Theater @ T...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,604,86,275,134,3,NaN,2012-10-02 09:55:23
10,951300678298886144,1515642730,2018-01-11 03:52:10,AlexandraAndoni,Client work takes us all over the map - today ...,low,0.0,NaN,NaN,0,...,28800.0,Hong Kong,en,995,210,464,489,29,NaN,2011-04-14 09:16:44
11,951300740743655424,1515642745,2018-01-11 03:52:25,JensensTennis,Awesome day at the Sydney International Wheelc...,low,0.0,NaN,NaN,0,...,-28800.0,Pacific Time (US & Canada),en,49,13,94,83,0,NaN,2017-11-02 22:03:22
17,951300915641901056,1515642787,2018-01-11 03:53:07,pavel6067,Drinking a Vilkmerges Sviesusis by Vilkmerges ...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,18843,40,90,50,11,NaN,2011-07-02 14:17:21
18,951300995216297989,1515642806,2018-01-11 03:53:26,AndieSoetaman,enjoying the view on top of a cliff next to Bo...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,8448,1283,251,399,9,NaN,2010-01-27 12:17:14
30,951301525636354048,1515642932,2018-01-11 03:55:32,Russy_Bear,üèÑüèº‚Äç‚ôÇÔ∏èüèñ#bondi #bondibeach #bondirescue #streeta...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,36,9,32,24,0,NaN,2014-01-26 20:17:12
40,951301855107342336,1515643011,2018-01-11 03:56:51,ATOAWASCA,Estoy autorizado a setirme bonito? @ Coogee Be...,low,0.0,NaN,NaN,0,...,-18000.0,Quito,en,109878,2177,2052,4630,7,NaN,2010-01-30 02:48:16
46,951302438291722241,1515643150,2018-01-11 03:59:10,recycologyy,Farewell to the #elvisexpress leaving #central...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,8875,300,75,14,52,NaN,2011-02-14 03:23:56
50,951302658366861318,1515643202,2018-01-11 04:00:02,susan_paget,A little update on my quest to take a break fr...,low,0.0,NaN,NaN,0,...,36000.0,Solomon Is.,en,3761,356,255,502,26,NaN,2012-09-21 07:25:31
54,951302785651310594,1515643233,2018-01-11 04:00:33,TrendsSydney,'crumble' & 'secrecy' are now trending in #Syd...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,75244,5972,1895,2,217,NaN,2010-03-17 06:52:47
57,951303017319550977,1515643288,2018-01-11 04:01:28,haidarasta,I'm at Westfield Eastgardens - @westfieldau in...,low,0.0,NaN,NaN,0,...,-32400.0,Alaska,en,74168,600,468,14471,0,NaN,2011-02-06 10:30:00
58,951303021039947777,1515643289,2018-01-11 04:01:29,LusciousKikis,Back to Gusto On the Beach...Banana Toffee Cak...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,3442,169,85,957,7,NaN,2011-12-21 23:44:39
72,951303424435544064,1515643385,2018-01-11 04:03:05,Mario426,@Girlie4 Safe and sound xxxxx (@ API Camellia ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,12837,430,2336,176,23,NaN,2009-02-27 06:22:39
73,951303433503387649,1515643387,2018-01-11 04:03:07,PairsonnalitesA,ASIA | AUNZ ‚Äî Maori teens pressured for nude ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1128837,3201,1444,0,154,NaN,2010-05-29 17:26:03
74,951303435437010946,1515643388,2018-01-11 04:03:08,PairsonnalitesA,ASIA | AUNZ ‚Äî Court puts fishhooks in taonga ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1128838,3201,1444,0,154,NaN,2010-05-29 17:26:03
75,951303437148286976,1515643388,2018-01-11 04:03:08,PairsonnalitesA,ASIA | AUNZ ‚Äî Maori artist brings Australia's...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1128839,3201,1444,0,154,NaN,2010-05-29 17:26:03
76,951303438477926401,1515643388,2018-01-11 04:03:08,PairsonnalitesA,ASIA | AUNZ ‚Äî Maori representation and social...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1128840,3201,1444,0,154,NaN,2010-05-29 17:26:03
78,951303483415826432,1515643399,2018-01-11 04:03:19,Iam_NaPha,Here I am!!!!! #PalmBeach üèñüòäüèù @ Barrenjoey Hea...,low,0.0,NaN,NaN,0,...,-28800.0,Pacific Time (US & Canada),th,18892,1366,412,802,3,NaN,2011-09-23 02:12:35
84,951303819811545089,1515643479,2018-01-11 04:04:39,SonnyManansala,Looking at #fingerwharfwoolloomooloo and #sydn...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,639,33,103,160,1,NaN,2011-10-15 10:34:46
90,951304131271999488,1515643553,2018-01-11 04:05:53,tmj_syd_sales,"If you're looking for work in #Sydney, NSW, ch...",low,0.0,NaN,NaN,0,...,-18000.0,Eastern Time (US & Canada),en,53,441,302,0,129,NaN,2009-04-27 01:14:54
98,951304554020331521,1515643654,2018-01-11 04:07:34,Donnabrasco310,A bunch of people have contacted me re my last...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,7402,330,491,892,16,NaN,2010-09-13 00:31:51
105,951304795293454336,1515643712,2018-01-11 04:08:32,atinyseed,"Ïã†ÏïΩ ÏÑ±ÏÑúÏóê Í∏∞Î°ùÎêú, ÏòàÏàòÎãòÏùÑ ÎØøÎäî ÏÑ±ÎèÑÎäî ÏùºÎ∞òÏù∏Îì§Í≥º Íµ¨Î≥ÑÎêúÎã§. Ïã†ÏïôÏùÑ ÎìúÎü¨ÎÇ¥Îäî Í≤É...",low,0.0,NaN,NaN,0,...,NaN,NaN,en,427,84,349,360,5,NaN,2015-02-15 08:22:10
112,951304951476768769,1515643749,2018-01-11 04:09:09,_the_epic_life,I don‚Äôt usually go down after a workout but th...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,1624,305,277,161,9,NaN,2011-02-28 00:24:15
154,951306237676851200,1515644056,2018-01-11 04:14:16,SnowdenParkes,Starting the New Year with the launch of Stell...,low,0.0,NaN,NaN,0,...,-36000.0,Hawaii,en,333,101,195,9,1,NaN,2011-05-09 14:18:10
162,951306595740409856,1515644141,2018-01-11 04:15:41,Yoen11,"I'm at Sydney CBD in Sydney, NSW https://t.co/...",low,0.0,NaN,NaN,0,...,25200.0,Jakarta,en,16625,160,1328,3,8,NaN,2010-12-27 00:54:48
164,951306757749518336,1515644180,2018-01-11 04:16:20,zinkandsons,Three-piece wedding suit for ZC cloth by @geof...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,506,366,35,5,12,NaN,2012-03-15 03:47:03
165,951306759645229061,1515644180,2018-01-11 04:16:20,recycologyy,Elvii selfie Sooo much fun today at Central S...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,8876,300,75,14,52,NaN,2011-02-14 03:23:56
167,951306832252989440,1515644197,2018-01-11 04:16:37,TrendsAustralia,"Menz FruChocs, @menzfruchocs is now trending i...",low,0.0,NaN,NaN,0,...,39600.0,Melbourne,en,106485,13934,3584,33,198,NaN,2010-11-03 01:33:33
185,951307447779647488,1515644344,2018-01-11 04:19:04,Yoen11,"I'm at @ColesOnline in Sydney, NSW https://t.c...",low,0.0,NaN,NaN,0,...,25200.0,Jakarta,en,16626,160,1328,3,8,NaN,2010-12-27 00:54:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522271,971872195306651648,1520547362,2018-03-08 22:16:02,M1trafficNSW,"The earlier BREAKDOWN Car, COWAN M1 just past ...",low,0.0,NaN,NaN,0,...,36000.0,Brisbane,en,18542,5448,2288,162,92,NaN,2012-06-24 11:23:08
522282,971872737991057410,1520547491,2018-03-08 22:18:11,erudenko,Putin is everywhere. #putin #putinmemes @ Sydn...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,1576,51,115,218,4,NaN,2009-12-25 13:18:24
522293,971873223855038465,1520547607,2018-03-08 22:20:07,seattoseat,"One of the hidden gems of sydney, look up and ...",low,0.0,NaN,NaN,0,...,-28800.0,Pacific Time (US & Canada),en,523,14,44,5,3,NaN,2015-10-30 10:51:24
522294,971873241596874753,1520547611,2018-03-08 22:20:11,sutto007,Sunrise Thursday 8th March 2018 -Day 67 of yea...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,9452,1834,282,1287,110,NaN,2008-05-20 09:34:49
522296,971873262979485699,1520547617,2018-03-08 22:20:17,DennisVollmer,Ahhh Friday how I‚Äôve missed you ü§ó Let‚Äôs jump i...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,25914,1085,2109,2294,111,NaN,2009-04-10 12:22:18
522310,971873605444362240,1520547698,2018-03-08 22:21:38,56Narwhals,"Below the poo, too bad for you. Above the crow...",low,0.0,NaN,NaN,0,...,39600.0,New Caledonia,en,2208,455,92,110,26,NaN,2014-02-03 09:28:20
522314,971873700449435648,1520547721,2018-03-08 22:22:01,pubtextiles,My colour reference I gave to Javed for this i...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,3674,2498,1933,100,31,NaN,2011-02-23 22:44:16
522330,971874396766982144,1520547887,2018-03-08 22:24:47,rickcaine9,‚ÄúThe fearful‚Äù ü¶Åü¶Åü¶Åü¶Åü¶Åü¶Åü¶Å #cowardlylion #thecoward...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,113,20,63,5,0,NaN,2013-06-15 05:32:09
522337,971874585388961792,1520547932,2018-03-08 22:25:32,GuyMorganArtist,G‚Äôday QE2! @ Sydney Harbour https://t.co/ukUOD...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,1881,82,50,125,12,NaN,2013-05-23 02:54:09
522345,971874949324529665,1520548019,2018-03-08 22:26:59,dionbp,"I'm at Headcase in Paddington, NSW https://t.c...",low,0.0,NaN,NaN,0,...,0.0,London,en,19091,1293,1434,6971,49,NaN,2009-02-21 23:34:03
522356,971875254875426817,1520548091,2018-03-08 22:28:11,Jeremyville,Last Bondi Beach lunch with dear friends @slin...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,8167,7041,81,118,280,NaN,2009-01-21 02:34:27
522375,971875902635245568,1520548246,2018-03-08 22:30:46,SUCC1864,Round 14 (Day 2) Match Reports https://t.co/t...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,2367,1324,164,432,11,NaN,2012-05-29 12:55:17
522383,971876228431978502,1520548324,2018-03-08 22:32:04,PairsonnalitesU,ASIA | AUNZ ‚Äî 81 per cent of world population...,low,0.0,NaN,NaN,1,...,-28800.0,Pacific Time (US & Canada),en,1322805,2825,2739,0,140,NaN,2010-10-26 15:04:54
522384,971876231778988032,1520548324,2018-03-08 22:32:04,PairsonnalitesU,ASIA | AUNZ ‚Äî Child protection report reveals...,low,0.0,NaN,NaN,1,...,-28800.0,Pacific Time (US & Canada),en,1322806,2825,2739,0,140,NaN,2010-10-26 15:04:54
522385,971876234098454528,1520548325,2018-03-08 22:32:05,PairsonnalitesU,ASIA | AUNZ ‚Äî Stark protection rates for indi...,low,0.0,NaN,NaN,1,...,-28800.0,Pacific Time (US & Canada),en,1322807,2825,2739,0,140,NaN,2010-10-26 15:04:54
522386,971876235973283841,1520548325,2018-03-08 22:32:05,PairsonnalitesU,ASIA | AUNZ ‚Äî June Oscar ensuring Indigenous ...,low,0.0,NaN,NaN,1,...,-28800.0,Pacific Time (US & Canada),en,1322808,2825,2739,0,140,NaN,2010-10-26 15:04:54
522387,971876248828833792,1520548328,2018-03-08 22:32:08,PairsonnalitesA,ASIA | AUNZ ‚Äî 81 per cent of world population...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1165455,3214,1438,0,154,NaN,2010-05-29 17:26:03
522388,971876251081236480,1520548329,2018-03-08 22:32:09,PairsonnalitesA,ASIA | AUNZ ‚Äî Child protection report reveals...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1165456,3214,1438,0,154,NaN,2010-05-29 17:26:03
522389,971876252285001729,1520548329,2018-03-08 22:32:09,PairsonnalitesA,ASIA | AUNZ ‚Äî Stark protection rates for indi...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1165457,3214,1438,0,154,NaN,2010-05-29 17:26:03
522391,971876253383852032,1520548330,2018-03-08 22:32:10,PairsonnalitesA,ASIA | AUNZ ‚Äî June Oscar ensuring Indigenous ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en-gb,1165458,3214,1438,0,154,NaN,2010-05-29 17:26:03
522399,971876511388241921,1520548391,2018-03-08 22:33:11,AltaModaSydney,H A P P Y F R I D A Y ! . We‚Äôre open to 7....,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,7374,517,1258,3540,70,NaN,2013-08-23 14:32:41
522409,971876731882803201,1520548444,2018-03-08 22:34:04,GuyMorganArtist,Life drawing at tombassprize tombasssculptures...,low,0.0,NaN,NaN,0,...,NaN,NaN,en,1882,82,50,125,12,NaN,2013-05-23 02:54:09
522411,971876809997471749,1520548462,2018-03-08 22:34:22,renee_glitch,It's my day off.. (@ Port Hacking Rd nr Box Rd...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,13174,103,157,40,13,NaN,2011-03-04 17:31:46
522416,971876910652370944,1520548486,2018-03-08 22:34:46,ayasasaki108,"I'm at Paddy's Markets in Haymarket, NSW https...",low,0.0,NaN,NaN,0,...,32400.0,Osaka,ja,5103,153,256,540,6,NaN,2011-01-16 18:27:04
522417,971876911495438336,1520548486,2018-03-08 22:34:46,SteveFaucette,The unveiling !! #formwork #aussie #visitnsw @...,low,0.0,NaN,NaN,0,...,39600.0,Canberra,en,1743,98,212,1740,9,NaN,2009-05-02 06:23:20
522420,971876996509786112,1520548507,2018-03-08 22:35:07,seb_ebikes,Pulling the rabbit out of the hat with the new...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,939,582,170,3,8,NaN,2012-06-28 06:32:06
522422,971877036678672384,1520548516,2018-03-08 22:35:16,ARTParkAust,#dreamtime #Edition 1 /12 #sculpture #silicon ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,1066,164,229,43,11,NaN,2014-06-19 23:52:29
522434,971877411066228736,1520548606,2018-03-08 22:36:46,GDSalamanca,Always an memorable experience here at @campos...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,1202,37,133,19,11,NaN,2010-05-20 05:36:39
522438,971877505090183171,1520548628,2018-03-08 22:37:08,1JYK1,#anothernightanothershow #latergram #lastnight...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,1799,158,179,609,10,NaN,2011-03-27 03:09:22
522439,971877523738030081,1520548632,2018-03-08 22:37:12,gregdimmock,Greg Dimmock the music man and A Swag Full of ...,low,0.0,NaN,NaN,0,...,39600.0,Sydney,en,3085,1204,1433,2,14,NaN,2009-02-03 00:02:30

In [22]:
#tweetdf.to_csv("tweets_w_lga.csv")
tweetdf = pd.read_csv('../../data/clean/tweets_w_lga.csv') # shortcut

In [23]:
aggdf = tweetdf[['lat','lng','text']].loc[~pd.isnull(tweetdf['lat'])].groupby(['lat','lng']).agg('count').reset_index()

In [24]:
posterdf = aggdf.loc[aggdf['text'] > 1000].merge(tweetdf,how='left',on=['lat','lng']).groupby('from_user_name').count()
posterdf.loc[posterdf['lat']> 20]

,lat,lng,text_x,Unnamed: 0,Unnamed: 0.1,id,time,created_at,text_y,filter_level,...,from_user_timezone,from_user_lang,from_user_tweetcount,from_user_followercount,from_user_friendcount,from_user_favourites_count,from_user_listed,from_user_withheld_scope,from_user_created_at,lga
from_user_name,,,,,,,,,,,,,,,,,,,,,
Allycat3015,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,0,21,21
BrownFormanJobs,92,92,92,92,92,92,92,92,92,92,...,92,92,92,92,92,92,92,0,92,92
CEBJobs,807,807,807,807,807,807,807,807,807,807,...,807,807,807,807,807,807,807,0,807,807
DJCMajor_Sydney,22,22,22,22,22,22,22,22,22,22,...,22,22,22,22,22,22,22,0,22,22
Delgado1ja,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,0,26,26
Happyscook,86,86,86,86,86,86,86,86,86,86,...,0,86,86,86,86,86,86,0,86,86
JobsAtContinuum,1669,1669,1669,1669,1669,1669,1669,1669,1669,1669,...,1669,1669,1669,1669,1669,1669,1669,0,1669,1669
JobsAtEricsson,36,36,36,36,36,36,36,36,36,36,...,36,36,36,36,36,36,36,0,36,36
JonnyStofko,31,31,31,31,31,31,31,31,31,31,...,0,31,31,31,31,31,31,0,31,31
Judotwin,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,0,33,33
KiaanTechboy,33,33,33,33,33,33,33,33,33,33,...,0,33,33,33,33,33,33,0,33,33
Nickey_is_Bored,36,36,36,36,36,36,36,36,36,36,...,0,36,36,36,36,36,36,0,36,36
Pairsonnalites,3780,3780,3780,3780,3780,3780,3780,3780,3780,3780,...,3780,3780,3780,3780,3780,3780,3780,0,3780,3780
PairsonnalitesA,7200,7200,7200,7200,7200,7200,7200,7200,7200,7200,...,7200,7200,7200,7200,7200,7200,7200,0,7200,7200
PairsonnalitesU,2954,2954,2954,2954,2954,2954,2954,2954,2954,2954,...,2954,2954,2954,2954,2954,2954,2954,0,2954,2954
SoleMateSneaker,59,59,59,59,59,59,59,59,59,59,...,0,59,59,59,59,59,59,0,59,59
StelliumLight,45,45,45,45,45,45,45,45,45,45,...,45,45,45,45,45,45,45,0,45,45
TrendsAustralia,1316,1316,1316,1316,1316,1316,1316,1316,1316,1316,...,1316,1316,1316,1316,1316,1316,1316,0,1316,1316
TrendsSydney,979,979,979,979,979,979,979,979,979,979,...,979,979,979,979,979,979,979,0,979,979
cielomar,46,46,46,46,46,46,46,46,46,46,...,46,46,46,46,46,46,46,0,46,46
cutesywootsy_au,48,48,48,48,48,48,48,48,48,48,...,0,48,48,48,48,48,48,0,48,48
fmatrix,45,45,45,45,45,45,45,45,45,45,...,45,45,45,45,45,45,45,0,45,45
iVidhiParmar,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,0,24,24
inforugbyreport,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,0,21,21
jksmini,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,0,100,100
ladonnarama,28,28,28,28,28,28,28,28,28,28,...,28,28,28,28,28,28,28,0,28,28
max_azman,122,122,122,122,122,122,122,122,122,122,...,0,122,122,122,122,122,122,0,122,122
moonlightdriive,34,34,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,0,34,34
ninabeilby,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,0,26,26
pearliestpearl,27,27,27,27,27,27,27,27,27,27,...,27,27,27,27,27,27,27,0,27,27
ravirockks,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,0,33,33
redkym,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,0,21,21
rickcaine9,83,83,83,83,83,83,83,83,83,83,...,0,83,83,83,83,83,83,0,83,83
sabascene,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,0,21,21
simplesocialsis,26,26,26,26,26,26,26,26,26,26,...,0,26,26,26,26,26,26,0,26,26
ssugar_shaun,27,27,27,27,27,27,27,27,27,27,...,0,27,27,27,27,27,27,0,27,27
tmj_syd_eng,370,370,370,370,370,370,370,370,370,370,...,370,370,370,370,370,370,370,0,370,370
tmj_syd_finance,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,0,54,54
tmj_syd_hrta,354,354,354,354,354,354,354,354,354,354,...,354,354,354,354,354,354,354,0,354,354
tmj_syd_it,236,236,236,236,236,236,236,236,236,236,...,236,236,236,236,236,236,236,0,236,236
tmj_syd_itdb,378,378,378,378,378,378,378,378,378,378,...,378,378,378,378,378,378,378,0,378,378
tmj_syd_itpm,143,143,143,143,143,143,143,143,143,143,...,143,143,143,143,143,143,143,0,143,143
tmj_syd_mgmt,322,322,322,322,322,322,322,322,322,322,...,322,322,322,322,322,322,322,0,322,322
tmj_syd_sales,345,345,345,345,345,345,345,345,345,345,...,345,345,345,345,345,345,345,0,345,345
tmj_syd_writing,371,371,371,371,371,371,371,371,371,371,...,371,371,371,371,371,371,371,0,371,371
twittypeach,34,34,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,0,34,34
unityfashionau,46,46,46,46,46,46,46,46,46,46,...,0,46,46,46,46,46,46,0,46,46
veganboypussy,23,23,23,23,23,23,23,23,23,23,...,23,23,23,23,23,23,23,0,23,23

In [7]:
import emot
text = "I love python üë® :-)"
print(emot.emoji(text))
print(emot.emoticons(text))

[{'value': 'üë®', 'location': [14, 14]}]
[{'value': ':-)', 'location': [16, 19]}]

In [8]:
tweetdf[['lga']].loc[~pd.isnull(tweetdf['lat'])].nunique()

lga    35
dtype: int64

In [9]:
tweets_aggdf = tweetdf[['lga','id']].loc[~pd.isnull(tweetdf['lat'])].groupby(['lga']).agg('count').reset_index()
tweets_aggdf.columns = ['lga','total_tweets']
tweets_aggdf.sort_values(by='total_tweets',ascending=False)

                     lga  total_tweets
29                Sydney         25874
32            Willoughby          6410
15            Inner West          3066
31              Waverley          3066
21      Northern Beaches          2811
22            Parramatta          1843
24              Randwick          1773
26                  Ryde          1465
28      Sutherland Shire          1395
34             Woollahra          1152
2             Botany Bay          1027
0              Blacktown           948
9             Cumberland           828
20          North Sydney           815
23               Penrith           801
25              Rockdale           687
13               Hornsby           587
30       The Hills Shire           567
19                Mosman           554
7   Canterbury-Bankstown           549
18             Liverpool           454
6             Canada Bay           416
11         Georges River           382
10             Fairfield           279
5           Campbelltown           276
4                 Camden           250
16           Ku-ring-gai           245
12            Hawkesbury           187
1         Blue Mountains           141
3                Burwood           139
27           Strathfield           119
17             Lane Cove           118
33           Wollondilly            49
8          Central Coast            44
14          Hunters Hill            40

In [11]:
tweeters_aggdf = tweetdf[['lga','from_user_name']].loc[~pd.isnull(tweetdf['lat'])].groupby(['lga']).agg({'from_user_name': lambda x: x.nunique()}).reset_index()
tweeters_aggdf.columns = ['lga','total_tweeters']
tweeters_aggdf.sort_values(by='total_tweeters',ascending=False)

                     lga  total_tweeters
29                Sydney            4531
31              Waverley            1087
15            Inner West             835
21      Northern Beaches             808
22            Parramatta             701
24              Randwick             634
2             Botany Bay             565
34             Woollahra             476
20          North Sydney             411
25              Rockdale             396
28      Sutherland Shire             324
0              Blacktown             321
19                Mosman             261
32            Willoughby             246
7   Canterbury-Bankstown             226
26                  Ryde             221
30       The Hills Shire             194
23               Penrith             184
6             Canada Bay             184
9             Cumberland             165
11         Georges River             139
13               Hornsby             125
18             Liverpool             115
10             Fairfield             113
16           Ku-ring-gai              89
3                Burwood              86
5           Campbelltown              78
27           Strathfield              64
1         Blue Mountains              57
17             Lane Cove              55
4                 Camden              50
12            Hawkesbury              47
8          Central Coast              24
14          Hunters Hill              24
33           Wollondilly              24

In [58]:
lang_ind_df = pd.merge(tweets_aggdf, tweeters_aggdf, on='lga')
lang_ind_df

                     lga  total_tweets  total_tweeters
0              Blacktown           948             321
1         Blue Mountains           141              57
2             Botany Bay          1027             565
3                Burwood           139              86
4                 Camden           250              50
5           Campbelltown           276              78
6             Canada Bay           416             184
7   Canterbury-Bankstown           549             226
8          Central Coast            44              24
9             Cumberland           828             165
10             Fairfield           279             113
11         Georges River           382             139
12            Hawkesbury           187              47
13               Hornsby           587             125
14          Hunters Hill            40              24
15            Inner West          3066             835
16           Ku-ring-gai           245              89
17             Lane Cove           118              55
18             Liverpool           454             115
19                Mosman           554             261
20          North Sydney           815             411
21      Northern Beaches          2811             808
22            Parramatta          1843             701
23               Penrith           801             184
24              Randwick          1773             634
25              Rockdale           687             396
26                  Ryde          1465             221
27           Strathfield           119              64
28      Sutherland Shire          1395             324
29                Sydney         25874            4531
30       The Hills Shire           567             194
31              Waverley          3066            1087
32            Willoughby          6410             246
33           Wollondilly            49              24
34             Woollahra          1152             476

In [59]:
demographics_df = pd.read_csv('../../data/clean/2016_demographics.csv')
demographics_df.rename(columns={'Tot_P_P_G01': 'population'}, inplace=True)
demographics_df[['lga','population']].sort_values(by='population',ascending=False)

                              lga  population
23           Canterbury-Bankstown      346302
9                       Blacktown      336962
25                  Central Coast      327736
86               Northern Beaches      252878
90                     Parramatta      226149
104              Sutherland Shire      218464
35                     Cumberland      216079
105                        Sydney      208374
69                      Liverpool      204326
126                    Wollongong      203630
40                      Fairfield      198817
64                 Lake Macquarie      197371
91                        Penrith      196066
56                     Inner West      182043
109               The Hills Shire      157243
21                   Campbelltown      157006
5                         Bayside      156058
84                      Newcastle      155411
43                  Georges River      146841
54                        Hornsby      142667
95                       Randwick      140660
61                    Ku-ring-gai      118053
97                           Ryde      116302
99                     Shoalhaven       99650
110                         Tweed       91371
73                      Mid-Coast       90303
22                     Canada Bay       88015
92        Port Macquarie-Hastings       78539
20                         Camden       78218
72                       Maitland       77305
12                 Blue Mountains       76904
123                    Willoughby       74302
30                  Coffs Harbour       72944
93                  Port Stephens       69556
98                   Shellharbour       68460
85                   North Sydney       67658
120                      Waverley       66812
51                     Hawkesbury       64592
115                   Wagga Wagga       62385
106             Tamworth Regional       59663
94   Queanbeyan-Palerang Regional       56027
27                       Cessnock       55560
127                     Woollahra       54240
0                          Albury       51076
28                Clarence Valley       50671
36                 Dubbo Regional       50077
125                   Wollondilly       48519
124                 Wingecarribee       47882
67                        Lismore       43135
2                         Ballina       41790
4               Bathurst Regional       41300
88                         Orange       40344
103                   Strathfield       40312
39                    Eurobodalla       37232
17                        Burwood       36809
65                      Lane Cove       36051
6                     Bega Valley       33253
18                          Byron       31556
46              Goulburn Mulwaree       29609
1               Armidale Regional       29449
59                        Kempsey       28885
76                         Mosman       28475
48                       Griffith       25641
74           Mid-Western Regional       24076
100                     Singleton       22987
96                Richmond Valley       22807
60                          Kiama       21464
68                        Lithgow       21090
101         Snowy Monaro Regional       20218
80                       Nambucca       19212
53                       Hilltops       18498
16                    Broken Hill       17708
57                       Inverell       16483
128                   Yass Valley       16142
79                   Muswellbrook       16086
89                         Parkes       14608
102                 Snowy Valleys       14395
112            Upper Hunter Shire       14112
55                   Hunters Hill       13999
19                        Cabonne       13386
75                   Moree Plains       13159
81                       Narrabri       13084
7                       Bellingen       12668
34                          Cowra       12460
41                     Federation       12277
49                       Gunnedah       12215
77                   Murray River       11680
66                         Leeton       11168
33           Cootamundra-Gundagai       11141
47             Greater Hume Shire       10351
42                         Forbes        9587
119            Warrumbungle Shire        9384
37                         Dungog        8975
62                         Kyogle        8940
38                   Edward River        8851
45              Glen Innes Severn        8836
8                        Berrigan        8462
113           Upper Lachlan Shire        7695
70               Liverpool Plains        7687
11                        Blayney        7257
122                     Wentworth        6794
108                   Tenterfield        6628
83                      Narromine        6444
58                          Junee        6295
63                        Lachlan        6194
107                        Temora        6110
117                       Walgett        6107
114                        Uralla        6048
10                          Bland        5955
82                     Narrandera        5853
87                         Oberon        5301
50                         Gwydir        5258
29                          Cobar        4647
31                       Coolamon        4315
44                      Gilgandra        4236
32                      Coonamble        3918
78                   Murrumbidgee        3836
121                        Weddin        3664
71                       Lockhart        3119
116                        Walcha        3092
52                            Hay        2946
118                        Warren        2732
24                     Carrathool        2719
13                          Bogan        2692
14                         Bourke        2634
3                       Balranald        2287
26                Central Darling        1833
15                     Brewarrina        1651
111       Unincorporated Far West        1056

In [60]:
lang_ind_df = pd.merge(lang_ind_df, demographics_df[['lga','population']],on='lga')
lang_ind_df['tweets_per_capita'] = lang_ind_df['total_tweets'] / lang_ind_df['population']
lang_ind_df['tweeters_per_capita'] = lang_ind_df['total_tweeters'] / lang_ind_df['population']

In [61]:
lang_ind_df

,lga,total_tweets,total_tweeters,population,tweets_per_capita,tweeters_per_capita
0,Blacktown,948,321,336962,0.002813,0.000953
1,Blue Mountains,141,57,76904,0.001833,0.000741
2,Burwood,139,86,36809,0.003776,0.002336
3,Camden,250,50,78218,0.003196,0.000639
4,Campbelltown,276,78,157006,0.001758,0.000497
5,Canada Bay,416,184,88015,0.004726,0.002091
6,Canterbury-Bankstown,549,226,346302,0.001585,0.000653
7,Central Coast,44,24,327736,0.000134,0.000073
8,Cumberland,828,165,216079,0.003832,0.000764
9,Fairfield,279,113,198817,0.001403,0.000568
10,Georges River,382,139,146841,0.002601,0.000947
11,Hawkesbury,187,47,64592,0.002895,0.000728
12,Hornsby,587,125,142667,0.004114,0.000876
13,Hunters Hill,40,24,13999,0.002857,0.001714
14,Inner West,3066,835,182043,0.016842,0.004587
15,Ku-ring-gai,245,89,118053,0.002075,0.000754
16,Lane Cove,118,55,36051,0.003273,0.001526
17,Liverpool,454,115,204326,0.002222,0.000563
18,Mosman,554,261,28475,0.019456,0.009166
19,North Sydney,815,411,67658,0.012046,0.006075
20,Northern Beaches,2811,808,252878,0.011116,0.003195
21,Parramatta,1843,701,226149,0.008149,0.003100
22,Penrith,801,184,196066,0.004085,0.000938
23,Randwick,1773,634,140660,0.012605,0.004507
24,Ryde,1465,221,116302,0.012597,0.001900
25,Strathfield,119,64,40312,0.002952,0.001588
26,Sutherland Shire,1395,324,218464,0.006385,0.001483
27,Sydney,25874,4531,208374,0.124171,0.021745
28,The Hills Shire,567,194,157243,0.003606,0.001234
29,Waverley,3066,1087,66812,0.045890,0.016270
30,Willoughby,6410,246,74302,0.086270,0.003311
31,Wollondilly,49,24,48519,0.001010,0.000495
32,Woollahra,1152,476,54240,0.021239,0.008776

In [65]:
lang_ind_df.to_csv("../../data/clean/language_independent_features.csv",index=False)