In [2]:
from nltk.tokenize.casual import casual_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import re
import pandas as pd
from string import punctuation
import os

input_filepath="../../data/clean/"
filename="filtered_tweets.csv"

In [3]:
tweetdf=pd.read_csv(os.path.join(input_filepath, filename),header=0)
tweetdf

,Unnamed: 0,Unnamed: 0.1,id,time,created_at,from_user_name,text,filter_level,possibly_sensitive,withheld_copyright,...,from_user_lang,from_user_tweetcount,from_user_followercount,from_user_friendcount,from_user_favourites_count,from_user_listed,from_user_withheld_scope,from_user_created_at,lga,latlng
0,0,0,951300429454831616,1515642671,2018-01-11 03:51:11,patientsafe3,@kaye_rolls @DrUmeshPrabhu @alisonleary1 @Matt...,low,NaN,NaN,...,en,27386,3790,4998,12523,117,NaN,2016-01-23 02:54:35,NaN,"(nan, nan)"
1,1,1,951300448031473664,1515642675,2018-01-11 03:51:15,Markfchris,Things to do on hot day in Sydney. @ Carriagew...,low,0.0,NaN,...,en,14953,695,1725,2615,62,NaN,2010-04-22 02:37:40,Sydney,"(-33.893658, 151.192032)"
2,2,2,951300464129093632,1515642679,2018-01-11 03:51:19,JasonStegeman,Harry probably wants his outfit back 😂🤠 https:...,low,0.0,NaN,...,en,7431,2263,2880,1029,150,NaN,2014-03-11 06:59:31,NaN,"(nan, nan)"
3,3,3,951300475034386432,1515642682,2018-01-11 03:51:22,RyanWilksPtyLtd,@RyanWilksPtyLtd has completed a #HVAC replace...,low,0.0,NaN,...,en,48,30,71,1,0,NaN,2012-06-26 23:52:20,NaN,"(nan, nan)"
4,4,4,951300560812113920,1515642702,2018-01-11 03:51:42,ZKII_,BB And The Blips x The Red Rattler Theater @ T...,low,0.0,NaN,...,en,604,86,275,134,3,NaN,2012-10-02 09:55:23,Inner West,"(-33.909939, 151.16366599999995)"
5,5,5,951300564435922944,1515642703,2018-01-11 03:51:43,ldeibe,@matonfender https://t.co/BF1Bp8z2b9,low,0.0,NaN,...,en,3769,1076,452,522,45,NaN,2009-09-01 05:32:16,NaN,"(nan, nan)"
6,6,6,951300578633687040,1515642706,2018-01-11 03:51:46,ladonnarama,@AaronManhattan https://t.co/kz4bzfJ7mu,low,0.0,NaN,...,en,6365,534,254,3690,33,NaN,2009-02-08 01:20:25,NaN,"(nan, nan)"
7,7,7,951300629212925953,1515642718,2018-01-11 03:51:58,MaskedNozza,I finished 2 days of of my workout regime in a...,low,NaN,NaN,...,en,1380,92,210,537,7,NaN,2014-01-30 01:47:42,NaN,"(nan, nan)"
8,8,8,951300630231969792,1515642719,2018-01-11 03:51:59,lmeyrick,@LagermenCC No one is... it would be unfair to...,low,NaN,NaN,...,en,12160,1821,983,4012,37,NaN,2009-08-13 23:25:51,NaN,"(nan, nan)"
9,9,9,951300666617573376,1515642727,2018-01-11 03:52:07,jessethanley,@moeamaya @AustinGrandt The exposure and exper...,low,NaN,NaN,...,en,9278,2486,139,26535,228,NaN,2009-10-19 07:37:16,NaN,"(nan, nan)"
10,10,10,951300678298886144,1515642730,2018-01-11 03:52:10,AlexandraAndoni,Client work takes us all over the map - today ...,low,0.0,NaN,...,en,995,210,464,489,29,NaN,2011-04-14 09:16:44,Ryde,"(-33.777198999999996, 151.124115)"
11,11,11,951300740743655424,1515642745,2018-01-11 03:52:25,JensensTennis,Awesome day at the Sydney International Wheelc...,low,0.0,NaN,...,en,49,13,94,83,0,NaN,2017-11-02 22:03:22,Blacktown,"(-33.718742, 150.922531)"
12,12,12,951300741255196673,1515642745,2018-01-11 03:52:25,LITDChisholm,@JustinTheTako @RumerPriestly @OfficialJlipper...,low,NaN,NaN,...,en,721,15,164,4195,0,NaN,2017-03-27 22:13:54,NaN,"(nan, nan)"
13,13,13,951300753838264322,1515642748,2018-01-11 03:52:28,dcagiunta,@embisshhh all from https://t.co/UY4t1aUArI 👀,low,1.0,NaN,...,en,112750,4880,901,72133,183,NaN,2011-01-07 09:54:13,NaN,"(nan, nan)"
14,14,14,951300793281343489,1515642758,2018-01-11 03:52:38,piadcsn,Inggit akoooo hahaha 😭 Pero iniki kasi 😭 https...,low,0.0,NaN,...,en,16187,537,328,9319,2,NaN,2009-07-15 08:27:09,NaN,"(nan, nan)"
15,15,15,951300864022528000,1515642774,2018-01-11 03:52:54,RobiUgh,@CharlesBulan_ ❤❤❤,low,NaN,NaN,...,en,7363,225,603,4999,0,NaN,2013-08-01 12:53:46,NaN,"(nan, nan)"
16,16,16,951300905579692032,1515642784,2018-01-11 03:53:04,AUSFestivus,"Ruh roh, I think someone pressed retweet on th...",low,0.0,NaN,...,en,21281,487,1067,2252,41,NaN,2009-03-10 10:32:28,NaN,"(nan, nan)"
17,17,17,951300915641901056,1515642787,2018-01-11 03:53:07,pavel6067,Drinking a Vilkmerges Sviesusis by Vilkmerges ...,low,0.0,NaN,...,en,18843,40,90,50,11,NaN,2011-07-02 14:17:21,Ryde,"(-33.807701, 151.08900500000001)"
18,18,18,951300995216297989,1515642806,2018-01-11 03:53:26,AndieSoetaman,enjoying the view on top of a cliff next to Bo...,low,0.0,NaN,...,en,8448,1283,251,399,9,NaN,2010-01-27 12:17:14,Waverley,"(-33.888908, 151.260635)"
19,19,19,951301019538882561,1515642812,2018-01-11 03:53:32,willbdamed,Disgusting @YouTube response to #loganpaul is ...,low,NaN,NaN,...,en,1111,481,1908,46,6,NaN,2009-02-03 20:21:27,NaN,"(nan, nan)"
20,20,20,951301059485483008,1515642821,2018-01-11 03:53:41,chalky021154,@surfbird03 All the problems we are having now...,low,NaN,NaN,...,en,28962,992,2203,1345,32,NaN,2009-11-17 05:59:41,NaN,"(nan, nan)"
21,21,21,951301145607065602,1515642842,2018-01-11 03:54:02,joaquinshanice_,Ghad aha man ka makakita ug 7k AUD run? 😭😭😭😭😭😭,low,NaN,NaN,...,en,14448,619,427,10460,1,NaN,2016-08-25 16:08:39,NaN,"(nan, nan)"
22,22,22,951301227777736704,1515642861,2018-01-11 03:54:21,ChocolateJohnny,@DimitieKendall Have a look at this live,low,NaN,NaN,...,en,16912,6681,3285,10241,618,NaN,2009-04-28 00:10:12,NaN,"(nan, nan)"
23,23,23,951301259247562752,1515642869,2018-01-11 03:54:29,jessethanley,"@kalenjordan @trackyourpos ""I just did somethi...",low,NaN,NaN,...,en,9279,2487,139,26537,228,NaN,2009-10-19 07:37:16,NaN,"(nan, nan)"
24,24,24,951301278063194117,1515642873,2018-01-11 03:54:33,cjwat,@SnoopWogg @2spiz @chris_gogos1 #Prolly 😌,low,NaN,NaN,...,en,6144,86,186,547,3,NaN,2012-07-14 01:11:29,NaN,"(nan, nan)"
25,25,25,951301299680690176,1515642878,2018-01-11 03:54:38,mikeaubrey2,@14luxor Yep,low,NaN,NaN,...,en,23270,1611,5003,94875,8,NaN,2017-01-15 00:44:30,NaN,"(nan, nan)"
26,26,26,951301407302344704,1515642904,2018-01-11 03:55:04,deniseshrivell,Same playbook as CFA. LNP Federal Ministers ly...,low,0.0,NaN,...,en,65128,6775,5246,80618,267,NaN,2008-09-02 10:16:22,NaN,"(nan, nan)"
27,27,27,951301409634267136,1515642905,2018-01-11 03:55:05,Kate_Carnell,@wickedd_childd @jessconnelly @amysmolcic Very...,low,NaN,NaN,...,en,3149,160,245,916,7,NaN,2009-12-28 10:20:08,NaN,"(nan, nan)"
28,28,28,951301419893534726,1515642907,2018-01-11 03:55:07,collao_xo,Is it just me or is it awk af when ppl post sh...,low,NaN,NaN,...,en,4595,392,326,5686,3,NaN,2010-11-07 05:31:51,NaN,"(nan, nan)"
29,29,29,951301450868539392,1515642914,2018-01-11 03:55:14,MisterGeek,"@Noahpinion Hey, at least they’re wealthy and ...",low,NaN,NaN,...,en,531,39,101,3082,13,NaN,2011-03-17 17:24:25,NaN,"(nan, nan)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498055,522426,522426,971877190932418561,1520548553,2018-03-08 22:35:53,CraigQtrmaine,@samishah Please... at least you lot get cast ...,low,NaN,NaN,...,en,1014,1267,991,1083,25,NaN,2013-09-08 23:09:00,NaN,"(nan, nan)"
498056,522427,522427,971877192685649920,1520548553,2018-03-08 22:35:53,JosieMcskimming,Just love ❤️ Jacinda. https://t.co/bJHPeovf0g,low,0.0,NaN,...,en,6913,556,832,4271,2,NaN,2016-12-18 00:37:30,NaN,"(nan, nan)"
498057,522428,522428,971877248704724993,1520548567,2018-03-08 22:36:07,philbertblogs1,https://t.co/hIbaCtkUHb oh and then the BIBE G...,low,0.0,NaN,...,en,2395,2,90,378,5,NaN,2017-12-29 20:27:25,NaN,"(nan, nan)"
498058,522429,522429,971877275913236480,1520548573,2018-03-08 22:36:13,pvbKPMG,Economic toll of gridlock - not to mention str...,low,0.0,NaN,...,en,1152,421,566,763,21,NaN,2015-03-13 00:03:20,NaN,"(nan, nan)"
498059,522430,522430,971877328488882176,1520548586,2018-03-08 22:36:26,owaisiawo,@MikeyGrice Thank heavens for being a caramel ...,low,0.0,NaN,...,en,33494,2203,3756,51992,53,NaN,2009-12-28 18:31:17,NaN,"(nan, nan)"
498060,522431,522431,971877343374467072,1520548589,2018-03-08 22:36:29,CartwheelPrint,Union watchdog charges taxpayers $500k to figh...,low,0.0,NaN,...,en,115075,9266,8572,70948,448,NaN,2010-02-16 02:37:57,NaN,"(nan, nan)"
498061,522432,522432,971877370440200192,1520548596,2018-03-08 22:36:36,LordRexWL,#TGIF This has been one of the weeks from hell...,low,NaN,NaN,...,en,25188,345,1620,42753,9,NaN,2009-05-11 11:53:08,NaN,"(nan, nan)"
498062,522433,522433,971877401721360384,1520548603,2018-03-08 22:36:43,walmason,Alan Jones pulling no punches on what’s going ...,low,0.0,NaN,...,en,5540,1523,1166,218,62,NaN,2009-01-13 04:42:15,NaN,"(nan, nan)"
498063,522434,522434,971877411066228736,1520548606,2018-03-08 22:36:46,GDSalamanca,Always an memorable experience here at @campos...,low,0.0,NaN,...,en,1202,37,133,19,11,NaN,2010-05-20 05:36:39,Sydney,"(-33.893051, 151.18313600000005)"
498064,522435,522435,971877469824274432,1520548620,2018-03-08 22:37:00,oliverdamian,@HPluckrose https://t.co/bM44JRr6Xz,low,0.0,NaN,...,en,15077,943,2914,3005,172,NaN,2008-05-28 10:39:07,NaN,"(nan, nan)"
498065,522436,522436,971877473246789634,1520548620,2018-03-08 22:37:00,Sattotah,الشي الثاني صار ⛅️ ... باقي بعد شي,low,NaN,NaN,...,en,43790,526,463,2770,7,NaN,2010-06-07 22:27:32,NaN,"(nan, nan)"
498066,522437,522437,971877491001384961,1520548625,2018-03-08 22:37:05,rob_mcknight,.@channelten have been planning to sack @JessR...,low,NaN,NaN,...,en,8563,4563,1738,3077,62,NaN,2010-04-13 04:12:59,NaN,"(nan, nan)"
498067,522439,522439,971877523738030081,1520548632,2018-03-08 22:37:12,gregdimmock,Greg Dimmock the music man and A Swag Full of ...,low,0.0,NaN,...,en,3085,1204,1433,2,14,NaN,2009-02-03 00:02:30,Bayside,"(-33.939632, 151.139359)"
498068,522440,522440,971877529786068992,1520548634,2018-03-08 22:37:14,LyndalSydney,@cherrypieit @GordonRamsay It's far too common...,low,NaN,NaN,...,en,1237,135,402,439,5,NaN,2012-08-27 12:19:18,NaN,"(nan, nan)"
498069,522441,522441,971877546189991936,1520548638,2018-03-08 22:37:18,Travelf1,@Jason_A_Swales @henryhopefrost Oh I’m so sad ...,low,NaN,NaN,...,en,8169,2861,361,11299,97,NaN,2010-07-28 21:29:46,NaN,"(nan, nan)"
498070,522442,522442,971877600120352769,1520548651,2018-03-08 22:37:31,owaisiawo,@JinnySkeans @itsyaboyjdubz Well atleast you h...,low,0.0,NaN,...,en,33495,2203,3756,51992,53,NaN,2009-12-28 18:31:17,NaN,"(nan, nan)"
498071,522443,522443,971877611335860224,1520548653,2018-03-08 22:37:33,JPhoenix7,"@rdryan33 @DetroitRedWings Thanks man, appreci...",low,NaN,NaN,...,en,47260,4048,4947,57880,53,NaN,2009-02-04 08:33:17,NaN,"(nan, nan)"
498072,522444,522444,971877656022081536,1520548664,2018-03-08 22:37:44,littlebufalo,@pierre_rochard Excuse my ignorance is this ab...,low,NaN,NaN,...,en,605,110,152,754,2,NaN,2017-06-30 05:00:26,NaN,"(nan, nan)"
498073,522445,522445,971877716839473152,1520548678,2018-03-08 22:37:58,KathKissell,Kelly ready for Commonwealth Games - bay 93.9 ...,low,0.0,NaN,...,en,4825,1853,3256,907,80,NaN,2008-11-05 08:07:23,NaN,"(nan, nan)"
498074,522446,522446,971877757612318720,1520548688,2018-03-08 22:38:08,maevemarsden,"#SingleAsianFemale at @BelvoirSt was warm, fun...",low,NaN,NaN,...,en,38179,2861,2480,17234,102,NaN,2011-02-23 10:44:24,NaN,"(nan, nan)"
498075,522447,522447,971877766625837056,1520548690,2018-03-08 22:38:10,SaramAndna,"朴정부, 탄핵기각 대비 ‘친위쿠데타’ 준비?… 국방부 “조사 착수” (출처 : 국민...",low,0.0,NaN,...,en,17812,1327,1570,3950,5,NaN,2010-11-13 07:25:35,NaN,"(nan, nan)"
498076,522448,522448,971877787760975872,1520548695,2018-03-08 22:38:15,concussionometr,#NRL takes hard line on #concussion chatter ht...,low,0.0,NaN,...,en,1355,57,143,12,1,NaN,2017-04-19 01:27:52,NaN,"(nan, nan)"
498077,522449,522449,971877808656891904,1520548700,2018-03-08 22:38:20,VickswFett,"The Last Jedi está bien chingona, quien no est...",low,NaN,NaN,...,es,6161,228,635,2065,16,NaN,2011-05-08 16:06:48,NaN,"(nan, nan)"
498078,522450,522450,971877869365284864,1520548715,2018-03-08 22:38:35,LeonardRGregory,#refsfault is the expert analysis for the FC l...,low,0.0,NaN,...,en,33212,1040,1288,33803,26,NaN,2012-09-13 23:27:57,NaN,"(nan, nan)"
498079,522451,522451,971877874662653952,1520548716,2018-03-08 22:38:36,aaronmdesouza,A bit late for 🇦🇺 but it's still #IWD2018 some...,low,0.0,NaN,...,en,604,248,198,1613,6,NaN,2016-10-19 16:35:55,NaN,"(nan, nan)"
498080,522452,522452,971877881272913920,1520548718,2018-03-08 22:38:38,SaramAndna,군인권센터 '친위쿠데타 모의한 군 수뇌부 엄단하라' (출처 : 뉴시스 | 네이버 뉴...,low,0.0,NaN,...,en,17813,1327,1570,3950,5,NaN,2010-11-13 07:25:35,NaN,"(nan, nan)"
498081,522453,522453,971878006678421504,1520548748,2018-03-08 22:39:08,Linny57284055,@AustralianLabor @Left_of_Labor @TurnbullMalco...,low,0.0,NaN,...,en,3174,69,242,2327,0,NaN,2013-05-19 10:55:28,NaN,"(nan, nan)"
498082,522454,522454,971878059019128833,1520548760,2018-03-08 22:39:20,owaisiawo,@JinnySkeans @itsyaboyjdubz That too 😜😁 https:...,low,0.0,NaN,...,en,33496,2203,3756,51993,53,NaN,2009-12-28 18:31:17,NaN,"(nan, nan)"
498083,522455,522455,971878104367968257,1520548771,2018-03-08 22:39:31,BadassMer,🔥thread 🔥#GirlsJustWannaHaveFunds🙌🏼 https://t....,low,0.0,NaN,...,en,107125,1330,1021,216820,103,NaN,2009-03-15 00:34:32,NaN,"(nan, nan)"
498084,522456,522456,971878118339223552,1520548774,2018-03-08 22:39:34,concussionometr,How #NFL’s #concussionprotocol really works ht...,low,0.0,NaN,...,en,1356,57,143,12,1,NaN,2017-04-19 01:27:52,NaN,"(nan, nan)"

In [4]:
by_tweeter = tweetdf.groupby(['lga','from_user_name'], as_index=False).agg({'text':lambda x:' '.join(x)})
#by_tweeter['text'] = by_tweeter.apply(lambda x: casual_tokenize(x['text'], strip_handles=True, reduce_len=True, preserve_case=False), axis=1)
by_tweeter

,lga,from_user_name,text
0,Bayside,0731Sus,うまそー！ #chocolatecafe#rockdale 場所: Sir Braxton ...
1,Bayside,11Bass,Sydney roads! #gottoloveapun #sydneycitylife #...
2,Bayside,17maez17,I’m gonna miss you so much my Simon😘😘😘 #lovelo...
3,Bayside,1JYK1,#flightattendantlife #InstructorLife @qantas #...
4,Bayside,3DogsBums,"@smh my experience, about 5,000 people waiting..."
5,Bayside,4fthawaiian,Had our favorite #fishandchips for dinner ❤️ @...
6,Bayside,545strat,Choc banana shake with choc almond milk...not ...
7,Bayside,577Express,暑い！！ 顔認証の自動入国審査できんかった。。 顔変わったかな(￣∇￣) #australi...
8,Bayside,76921890,I'm at Sydney International Airport - Arrivals...
9,Bayside,ACampbell47,Just a quick trip up to #Brisbane and back tod...
10,Bayside,AJauntWithJoy,🎶 I’m way too good at goodbye... ↠↠↠↠↠↠↠↠↠ • ↞...
11,Bayside,APRILAJJJ,Relax. Enjoy. Have fun. 😉😉😉👍👌 #shiplife #tyl #...
12,Bayside,ASephiroth,Happy Australia Day! Longest flight I’ve ever...
13,Bayside,AarontheBaaron,"Oi oi oi (at @SydneyAirport in Mascot, NSW w/ ..."
14,Bayside,AbdTorah,Be who you are... and say what you feel.. beca...
15,Bayside,Adam_OH,Goodbye Sydney! You’ve been my home for 20 yea...
16,Bayside,AdrianMorte,Concrete... @ Sydney Kingsford Smith Internati...
17,Bayside,Aipmaulana,At @sydneyairport — https://t.co/8zHnkDv7d7
18,Bayside,AirHarajukuGirl,"I'm at @SydneyAirport in Mascot, NSW https://t..."
19,Bayside,AlbertJllo,Good morning #Sydney #morningRun @ Brighton-Le...
20,Bayside,AlexCanion,MBB the_scoon #mbb #banner #boi @ Sydney Airpo...
21,Bayside,AlexaNoelli,I'm at Sydney International Airport - Departur...
22,Bayside,AliChahrour94,New Year Same Me 🙏 #Bali #Holiday #2k18 ✈️✈️ ...
23,Bayside,Alinta_Chidzey,World cruisin’ with these guys is as good as #...
24,Bayside,Alttitude1,#sunrise t3 @qantas qantas_sydney qantascabin...
25,Bayside,Always_Blessed,Welcoming committee ~ #happyreunion with my m...
26,Bayside,AmeliaERyan,This kid is a total dream. Not one peep (excep...
27,Bayside,AndrewMDesmond,Paying for extra leg room in cattle class all ...
28,Bayside,AndyPreston,Thank goodness for Qantas recognising my Qatar...
29,Bayside,AngkieYudistia,Never ending learning. Itu pelajaran yang aku ...
...,...,...,...
14401,Woollahra,syazlicious,Sunny afternoon catch up 💛💛 @ Watsons Bay Bout...
14402,Woollahra,sydguitarschool,Duo Agostino with Rachel Scott (cello) before ...
14403,Woollahra,sydneyysj,there’s snow place like home!!! ❄️ ⛄️ @ Fred's...
14404,Woollahra,tara891,💍👰🏼 @ Dunbar House https://t.co/JNtYnSusjZ
14405,Woollahra,taylawatterson,Let’s just take like a candid shot. @ Watsons ...
14406,Woollahra,thatchertime,One foot Sunday #beach #campcove #summer #crac...
14407,Woollahra,the_pherk,An extremely dangerous breed of shark swimming...
14408,Woollahra,therealRiveLL,Good memories.. #Australia #holidays #family ...
14409,Woollahra,thevignetteroom,Just a little shuffle upstairs this week! 👌 @ ...
14410,Woollahra,tildaswagton,🍁🔴What a salty beach 🔴🍁 @ Red Leaf Beach https...
14411,Woollahra,tjrnichols,Had a truly spectacular day on the harbour yes...
14412,Woollahra,travel_daily,What a beautiful personalised gift for guests ...
14413,Woollahra,traxlmaz,Kutti Beach #vaucluse #sydney #hidden #seclude...
14414,Woollahra,trudderrs,The CBD on the horizon #watsonsbay #nsw #visit...
14415,Woollahra,tuppaware,Just posted a photo @ Gap Bluff https://t.co/M...
14416,Woollahra,tzungtzuli,走到 walsons bay 后面的海军基地，然后被拦住了😂 (@ HMAS Watson ...
14417,Woollahra,urbanphaedrus,Doing a last minute shop for dinner at our pla...
14418,Woollahra,valenbozzaotra,La nostalgia llega con puntualidad en Darling ...
14419,Woollahra,waltfrasier,"Marina @ Watsons Bay, New South Wales, Austral..."
14420,Woollahra,woyced,Not a bad view for the evening! Thanks Luke! @...
14421,Woollahra,wrtsmith,Sydney harbor by boat with the most important ...
14422,Woollahra,xtinakill32,Burning my passport so I never have to leave @...
14423,Woollahra,yatyeung32,"#sydney #watsonsbay #sunset @ Watsons Bay, New..."
14424,Woollahra,ydonna_official,“The best preparation for tomorrow is doing yo...
14425,Woollahra,yogirandomsoul,"As molly would say, do yourself a favour and g..."
14426,Woollahra,zac_sykes,This dickhead trying to get the perfect pictur...
14427,Woollahra,zagundo,14th trip to Camp Cove this year. That’s a 66%...
14428,Woollahra,zedforzane,. n o e f f e c t Live Laugh Love If that doe...
14429,Woollahra,zhiana,"Happy birthday, Dad. Enjoying the overcast hum..."
14430,Woollahra,zoeryanmusic,Just witnessed the most beautiful celebration ...

In [6]:
def tokenize(text):
    return casual_tokenize(text, strip_handles=True, reduce_len=True, preserve_case=False)

tfidf = TfidfVectorizer(tokenizer=tokenize, stop_words='english')
tfs = tfidf.fit_transform(by_tweeter['text'])
print(tfs.shape[0])

features = np.array(tfidf.get_feature_names())

14431

In [8]:
def top_tfidf_feats(row, features, top_n=25):
    topn_ids = np.argsort(row)[::-1][:top_n]
    top_feats = [(features[i], row[i]) for i in topn_ids]
    df = pd.DataFrame(top_feats)
    df.columns = ['feature', 'tfidf']
    return df

#Return top features amongst documents in rows indentified by indices in grp_ids
def top_mean_feats(tfs, features, grp_ids=None, min_tfidf=0.1, top_n=25):
    if grp_ids:
        D = tfs[grp_ids].toarray()
    else:
        D = tfs.toarray()

    D[D < min_tfidf] = 0
    tfidf_means = np.mean(D, axis=0)
    return top_tfidf_feats(tfidf_means, features, top_n)

In [10]:
top_mean_feats(tfs,features, top_n=50)

       feature     tfidf
0            ,  0.026096
1            !  0.022365
2       sydney  0.021328
3            .  0.021080
4            @  0.016130
5          nsw  0.015761
6        beach  0.013134
7            ’  0.012944
8          i'm  0.012375
9      #sydney  0.010923
10           -  0.010585
11           ️  0.010323
12       bondi  0.009810
13           …  0.009718
14         new  0.009378
15   australia  0.009194
16           (  0.008879
17         ...  0.008727
18           )  0.008647
19       south  0.007921
20         day  0.007830
21           s  0.007519
22       wales  0.007512
23        just  0.006871
24     harbour  0.006736
25  #australia  0.006705
26        park  0.006304
27       photo  0.005856
28           :  0.005635
29           ?  0.005566
30       house  0.005399
31      posted  0.005346
32       opera  0.005324
33           🇺  0.005182
34           🇦  0.005160
35      mascot  0.004849
36           /  0.004838
37       manly  0.004809
38           &  0.004806
39       night  0.004624
40           ❤  0.004586
41       great  0.004568
42       today  0.004567
43        time  0.004411
44           •  0.004402
45       happy  0.004377
46        love  0.004177
47     airport  0.004099
48      coogee  0.003977
49           —  0.003910